sudo: required
services:
  - docker

before_install:
  - docker build -t vic0707/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vic0707/react-test npm test -- --coverage

after_success:
  - docker build -t vic0707/multi-client ./client
  - docker build -t vic0707/multi-nginx ./nginx
  - docker build -t vic0707/multi-server ./server
  - docker build -t vic0707/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vic0707/multi-client
  - docker push vic0707/multi-nginx
  - docker push vic0707/multi-server
  - docker push vic0707/multi-worker

deploy:
  provider: elasticbeanstalk
  regoin: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-881886524550
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
